name: Web

on:
  push:
    branches: [main]

jobs:
  pages:
    runs-on: ubuntu-latest
    env:
      USE_BASE_PATH: true
      VITE_PEER_HOST: 0.peerjs.com
      VITE_PEER_PORT: 443
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm install -g npm@7.24.2
      - run: npm ci
      - run: npm run web.build
      - uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: '/service-worker.js'
          replace: '/wordgames/service-worker.js'
          include: '**/*.html'
          regex: false

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
